baseURL = "https://denx.netlify.app/"
languageCode = "ja"
title = "電気情報研究会 DENX"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
pluralizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "denx"
    description = "同志社大学 電気情報研究会"
    copyright = "同志社大学 電気情報研究会"
    favicon = "/image/icon.ico"
    githubUsername = "#"
    accent = "#FF9D00"
    showBorder = true
    backgroundColor = "white"
    font = "Sawarabi+Gothic" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    custom_css = ["css/navbar.css", "css/heading.css", "css/send-button.css", "css/banner.css", "css/table.css", "css/illust-layout.css"]
    custom_js = ["js/menus.js"]

    YouTubeLink = "https://www.youtube.com/embed/S1N913eKvoQ"
    news = [
      "2025/01/11: 1月総会",
      "2024/12/30: コミックマーケット105 2日目サークル出展",
      "2024/12/14: 12月総会",
      "2024/11/28: 同志社EVE 3日目参加",
      "2024/11/27: 同志社EVE 2日目参加",
      "2024/11/09: ハロウィンパーティー",
      "2024/11/09: 11月総会",
      "2024/10/12: 10月総会",
      "2024/09/14: 夏開発成果発表",
      "2024/09/14: 9月総会",
      "2024/09/14: 夏開発最終日",
      "2024/09/08: KC3 2日目",
      "2024/09/07: KC3 1日目",
      "2024/08/31: 夏開発開始日",
      "2024/08/30: 夏合宿最終日",
      "2024/08/28: 夏合宿開始日",
      "2024/08/10: 8月総会",
      "2024/07/13: 7月総会",
      "2024/06/29: 6月ハッカソン成果発表",
      "2024/06/23: 6月ハッカソン終了日",
      "2024/06/16: 6月ハッカソン開始日",
      "2024/06/08: 6月総会",
      "2024/05/26: 高槻観光",
      "2024/05/25: ゲーム大会",
      "2024/05/11: 5月総会",
      "2024/04/28: 京都観光",
      "2024/04/27: 動画編集講座",
      "2024/04/25: Unity音ゲー講座",
      "2024/04/24: 学生支援課とコラボ ゲーム体験会,作品展示開催",
      "2024/04/23: Unity講座",
      "2024/04/21: オンライン説明会",
      "2024/04/20: 対面説明会(今出川校地)",
      "2024/04/19: GitHub講座",
      "2024/04/16: Python講座",
      "2024/04/15: 自作コントローラー披露(京田辺校地)",
      "2024/04/14: 環境構築会",
      "2024/04/13: 4月総会",
      "2024/04/13: 対面説明会(京田辺校地)",
      "2024/04/09: Unity講座",
      "2024/04/08: DTM講座",
      "2024/04/07: 環境構築会",
      "2024/04/07: オンライン説明会",
      "2024/04/06: ブース設置最終日",
      "2024/04/02: ブース設置開始日",
      "2024/03/31: 春ハッカソン最終日",
      "2024/03/09: 3月総会",
      "2024/03/03: 春ハッカソン中間発表",
      "2024/02/10: 春ハッカソン開始日",
      "2024/02/10: 2月総会",
      "2024/01/16: 学生支援課とのコラボ ゲーム体験会開催",
      "2024/01/13: 1月総会",
      "2023/12/31: コミックマーケット103 2日目サークル出展",
      "2023/12/26: クリスマスパーティー",
      "2023/12/09: 12月総会",
      "2023/11/28: 同志社EVE 3日目参加",
      "2023/11/27: 同志社EVE 2日目参加",
      "2023/11/26: 同志社EVE 1日目参加",
      "2023/11/11: 11月総会",
      "2023/10/28: ハロウィンパーティー",
      "2023/10/14: 10月総会",
    ]

[[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/denx-official"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://x.com/DENX_jp"
    name = "X"
    weight = 2
