baseURL = "https://denx.netlify.app/"
languageCode = "ja"
title = "電気情報研究会 DENX"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
pluralizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "denx"
    description = "同志社大学 電気情報研究会"
    copyright = "同志社大学 電気情報研究会"
    favicon = "/image/icon.ico"
    githubUsername = "#"
    accent = "#FF9D00"
    showBorder = true
    backgroundColor = "white"
    font = "Sawarabi+Gothic" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    custom_css = ["css/navbar.css", "css/heading.css", "css/send-button.css", "css/banner.css", "css/table.css", "css/illust-layout.css"]
    custom_js = ["js/menus.js"]

    YouTubeLink = "https://www.youtube.com/embed/S1N913eKvoQ"
    news = [
      "2024/04/28: 京都観光",
      "2024/04/27: 動画編集講座",
      "2024/04/25: Unity音ゲー講座",
      "2024/04/24: 学生支援課とコラボ ゲーム体験会,作品展示開催",
      "2024/04/23: Unity講座",
      "2024/04/21: オンライン説明会",
      "2024/04/20: 対面説明会(今出川校地)",
      "2024/04/19: GitHub講座",
      "2024/04/16: Python講座",
      "2024/04/15: 自作コントローラー披露(京田辺校地)",
      "2024/04/14: 環境構築会",
      "2024/04/13: 4月総会" ,
      "2024/04/13: 対面説明会(京田辺校地)" ,
      "2024/04/09: Unity講座" ,
      "2024/04/08: DTM講座" ,
      "2024/04/07: 環境構築会",
      "2024/04/07: オンライン説明会" ,
      "2024/04/06: ブース設置最終日" ,
      "2024/04/02: ブース設置開始日" ,
      "2024/03/31: 春ハッカソン最終日" ,
      "2024/03/09: 3月総会" ,
      "2024/03/03: 春ハッカソン中間発表" ,
      "2024/02/10: 春ハッカソン開始日" ,
      "2024/02/10: 2月総会" ,
      "2024/01/16: 学生支援課とのコラボ ゲーム体験会開催" ,
      "2024/01/13: 1月総会" ,
      "2023/12/31: コミックマーケット103 2日目サークル出展" ,
      "2023/12/26: クリスマスパーティー" ,
      "2023/12/09: 12月総会" ,
      "2023/11/28: 同志社EVE 3日目参加" ,
      "2023/11/27: 同志社EVE 2日目参加" ,
      "2023/11/26: 同志社EVE 1日目参加" ,
      "2023/11/11: 11月総会" ,
      "2023/10/28: ハロウィンパーティー" ,
      "2023/10/14: 10月総会" ,
      "2023/10/08: 秋ハッカソン最終日" ,
      "2023/09/25: 秋ハッカソン開始日" ,
      "2023/09/16: 9月総会" ,
      "2023/09/10: KC3 2日目参加" ,
      "2023/09/09: KC3 1日目参加" ,
      "2023/08/30: 夏合宿最終日" ,
      "2023/08/28: 夏合宿開始日" ,
      "2023/08/11: 8月ハッカソン成果発表" ,
      "2023/08/11: 8月ハッカソン最終日" ,
      "2023/08/05: 8月ハッカソン開始日" ,
      "2023/07/08: 7月総会" ,
      "2023/06/25: 6月ミニハッカソン成果発表" ,
      "2023/06/24: 6月ミニハッカソン最終日" ,
      "2023/06/18: 6月ミニハッカソン開始日" ,
      "2023/06/10: 6月総会" ,
      "2023/05/13: 5月総会" ,
      "2023/05/04: 新入生 オンライン交流会" ,
      "2023/05/04: 3Days開発会 最終日" ,
      "2023/05/02: 3Days開発会 開始日" ,
      "2023/05/01: 難波観光" ,
      "2023/05/01: 京都観光" ,
      "2023/04/29: 新入生 対面交流会" ,
      "2023/04/27: Unity講座" ,
      "2023/04/26: DTM講座" ,
      "2023/04/23: web説明会" ,
      "2023/04/22: 3DCG講座" ,
      "2023/04/22: 競技プログラミング講座" ,
      "2023/04/17: 2Dゲーム制作講座" ,
      "2023/04/16: イラスト講座" ,
      "2023/04/15: 対面説明会" ,
      "2023/04/15: 4月総会" ,
      "2023/04/10: C言語講座" ,
      "2023/04/09: Python講座" ,
      "2023/04/07: web説明会" ,
      "2023/04/06: ブース設置最終日" ,
      "2023/04/03: 新歓ブース設置" ,
      "2023/03/11: 3月総会" ,
      "2023/03/01: UE5合同勉強会" ,
      "2023/02/28: 開発会発表" ,
      "2023/02/14: 2月総会" ,
      "2023/01/15: Blender&イラスト合同勉強会" ,
      "2023/01/14: 1月総会" ,
      "2022/12/18: UE5合同勉強会",
      "2022/12/10: 12月総会",
      "2022/11/26: 同志社EVE参加",
    ]

[[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/denx-official"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/DENX_JP"
    name = "twitter"
    weight = 2
