baseURL = "https://denx.netlify.app/"
languageCode = "ja"
title = "電気情報研究会 DENX"
theme = "minimal"
disqusShortname = "username" # delete this to disable disqus comments
googleAnalytics = ""
pluralizeListTitles = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
    author = "denx"
    description = "同志社大学 電気情報研究会"
    copyright = "同志社大学 電気情報研究会"
    favicon = "/image/icon.ico"
    githubUsername = "#"
    accent = "#FF9D00"
    showBorder = true
    backgroundColor = "white"
    font = "Sawarabi+Gothic" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]
    custom_css = ["css/navbar.css", "css/heading.css", "css/send-button.css", "css/banner.css", "css/table.css", "css/illust-layout.css"]
    custom_js = ["js/menus.js"]

    YouTubeLink = "https://www.youtube.com/embed/S1N913eKvoQ"
    news = [
      "2023/05/04: 新入生 オンライン交流会" ,
      "2023/05/04: 3Days開発会 最終日" ,
      "2023/05/02: 3Days開発会 開始日" ,
      "2023/05/01: 難波観光" ,
      "2023/05/01: 京都観光" ,
      "2023/04/29: 新入生 対面交流会" ,
      "2023/04/27: Unity講座" ,
      "2023/04/26: DTM講座" ,
      "2023/04/23: web説明会" ,
      "2023/04/22: 3DCG講座" ,
      "2023/04/22: 競技プログラミング講座" ,
      "2023/04/17: 2Dゲーム制作講座" ,
      "2023/04/16: イラスト講座" ,
      "2023/04/15: 対面説明会" ,
      "2023/04/15: 4月総会" ,
      "2023/04/10: C言語講座" ,
      "2023/04/09: Python講座" ,
      "2023/04/07: web説明会" ,
      "2023/04/06: ブース設置最終日" ,
      "2023/04/03: 新歓ブース設置" ,
      "2023/03/11: 3月総会" ,
      "2023/03/01: UE5合同勉強会" ,
      "2023/02/28: 開発会発表" ,
      "2023/02/14: 2月総会" ,
      "2023/01/15: Blender&イラスト合同勉強会" ,
      "2023/01/14: 1月総会" ,
      "2022/12/18: UE5合同勉強会",
      "2022/12/10: 12月総会",
      "2022/11/26: 同志社EVE参加",
      "2022/11/05: 11月総会",
      "2022/10/08: 10月総会",
      "2022/09/17: 9月総会",
      "2022/09/10: KC3参加",
      "2022/08/29: 開発会発表",
      "2022/08/22: 8月総会",
      "2022/07/09: 7月総会",
      "2022/06/26: ゲーム制作講座 #4",
      "2022/06/19: ゲーム制作講座 #3",
      "2022/06/11: 6月総会",
      "2022/05/29: ゲーム制作講座 #2",
      "2022/05/22: ゲーム制作講座 #1",
      "2022/05/14: 5月総会",
      "2022/05/08: イラスト講座 #4",
      "2022/05/07: 交流会 #2",
      "2022/05/04: イラスト講座 #3",
      "2022/05/03: 交流会 #1",
    ]

[[menu.main]]
#     url = "/"
#     name = "Home"
#     weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "https://github.com/denx-official"
    name = "github"
    weight = 1

[[menu.icon]]
    url = "https://twitter.com/DENX_JP"
    name = "twitter"
    weight = 2
